---
- name: add public keys for ssh
  hosts: all
  tasks:
    - name: add all keys in folder
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', item) }}"
      loop: "{{ lookup('fileglob', 'pubkeys/*.pub', wantlist=true)}}"