Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "addpublickeys"
  config.vm.network :private_network, type: "dhcp"
  config.vm.provision :ansible, playbook: "add-public-keys.yml"
end